spring:
  rabbitmq:
    #host: localhost
    host: 192.168.0.144
    port: 5672
    username: admin
    password: admin
    virtual-host: /
    chat-queue-name: chat.queue
    chat-exchange-name: chat.topic
    chat-routing-key: room.*
    stomp-relay-port: 61613
    stomp-application-destination-prefixes:
      - /pub
    stomp-end-point:
      - /stomp/chat
    stomp-allowed-origin-patterns:
      - "*"
    stomp-broker-relay:
      - /exchange

  datasource:
    url: jdbc:mariadb://localhost:3306/rabbitmq_chat
    username: root
    password: green502
    driver-class-name: org.mariadb.jdbc.Driver
    #driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  jpa:
    open-in-view: false # api 의 요청부터 응답까지 영속성 컨텍스트가 유지 default = true
    hibernate:
      dialect: org.hibernate.dialect.MySQLInnoDBDialect
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        #default_batch_fetch_size: 100
    generate-ddl: true
app:
  jwt:
    secret: DaeguGreenArtAcademyClass502RoomForJavaSpringBootFighting
    header-scheme-name: Authorization
    token-type: Bearer
    access-token-expiry: 72000000
    refresh-token-expiry: 1296000000

file:
  dir: D:/download/rabbitmqChat/